package main

const (
	debugFile              = "debug.log"
	emptyString            = ""
	equalSignString        = "="
	zeroRune               = '0'
	longSpace              = "                                                                " // 64 spaces
	optionCursorPrefix     = "→ "
	optionEmptyPrefix      = "  "
	optionCursorPrefixLen  = len(optionCursorPrefix)
	optionEmptyPrefixLen   = len(optionEmptyPrefix)
	newlineRune            = '\n'
	newlineString          = "\n"
	tabString              = "\t"
	singleSpaceRune        = ' '
	singleSpaceString      = " "
	threeDots              = "..."
	fourDots               = "...."
	threeHyphens           = "---"
	poolThreshold1         = 1024
	poolThreshold2         = 2048
	poolThreshold3         = 3072
	poolThreshold4         = 4096
	poolThreshold6         = 6144
	poolThreshold8         = 8192
	poolThreshold12        = 12288
	poolThreshold16        = 16384
	poolThreshold20        = 20480
	overhead               = 64
	path                   = "strings.json"
	saveFile               = "save.txt"
	turnPlayer             = 1
	turnDealer             = 2
	two                    = "2"
	three                  = "3"
	four                   = "4"
	five                   = "5"
	six                    = "6"
	seven                  = "7"
	eight                  = "8"
	nine                   = "9"
	ten                    = "10"
	jack                   = "J"
	queen                  = "Q"
	king                   = "K"
	ace                    = "A"
	heart                  = "♥"
	diamond                = "♦"
	club                   = "♣"
	spade                  = "♠"
	phaseConfig            = 1
	phasePlay              = 2
	phaseEnd               = 3
	phaseBet               = 4
	pen00                  = " 0 %"
	pen25                  = "25 %"
	pen50                  = "50 %"
	pen75                  = "75 %"
	payout32               = "3:2"
	payout75               = "7:5"
	payout65               = "6:5"
	configStepStartUp      = 0
	configStepH17          = 1
	configStepDecks        = 2
	configStepPen          = 3
	configStepLoad         = 4
	configStepLoadFail     = 5
	configStepStartConfirm = 6
	configStepLoadConfirm  = 7
	configStepPayout       = 8
	// Custom base32 character set: digits 1-9, uppercase letters excluding i,o,q in upper case
	base32Chars = "123456789ABCDEFGHJKLMNPRSTUVWXYZ"
	// Custom base45 character set: digits 1-9, uppercase and lowercase letters excluding i,l,m,n,o,q,u,v from both cases
	base45Chars         = "123456789ABCDEFGHJKPRSTWXYZabcdefghjkprstwxyz"
	naturalBlackjackWin = 1
	normalWin           = 2
	normalLoose         = 3
	normalDraw          = 4
	doubleWin           = 5
	doubleLoose         = 6
	doubleDraw          = 7
	surrender           = 8
	bet10               = "10"
	bet20               = "20"
	bet30               = "30"
	bet40               = "40"
	bet50               = "50"
)
